version: "3.9"
services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data/pg/data:/var/lib/postgresql/data
      - ./data/pg/conf:/etc/postgresql/data
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs